name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        os: [iOS, macOS]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Recovering Cache
        uses: actions/cache@v1.1.2
        id: cache
        with:
          path: Carthage
          key: ${{ matrix.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: |
            ${{ matrix.os }}-carthage-
      - name: Building Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: carthage build --no-use-binaries --platform ${{ matrix.os }}
      - name: Installing Bundler
        run: bundle install
      - name: Build and Test
        run: bundle exec fastlane scan --scheme NEKit-${{ matrix.os }}
